<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>

    <pre data-bind="text: JSON.stringify(config, null, 4)"></pre>

    <pre data-bind="text: output"></pre>

    <table>
        <tr>
            <th data-bind="i18n: 'Currency to'"></th>
            <th data-bind="i18n: 'Rate'"></th>
        </tr>
        <!-- ko foreach: exchangeRates -->
        <tr>
            <td data-bind="text: currencyTo"></td>
            <td data-bind="text: rate"></td>
        </tr>
        <!-- /ko -->
    </table>

    <ul data-bind="foreach: values">
        <li data-bind="text: $data"></li>
    </ul>
</div>

<div data-bind="scope: 'es5Observable'">
    <table data-bind="foreach: items">
        <tr>
            <td data-bind="text: name"></td>
            <td data-bind="text: qty"></td>
            <td data-bind="text: price"></td>
            <td data-bind="text: $parent.rowTotal($data)"></td>
        </tr>
    </table>
    <div>
        Additional Charge: <span data-bind="text: additionalCharge"></span>
    </div>
    <div>
        <strong>Total: <span data-bind="text: total()"></span></strong>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimple": {
                        "component": "Matozan_MagentoJs/js/knockout/plain-view-model",
                        "baseUrl": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
                    },
                    "es5Observable": {
                        "component": "Matozan_MagentoJs/js/knockout/es5-observables"
                    }
                }
            }
        }
    }
</script>
