<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div data-bind="scope: 'startSimple'">
    <h2 data-bind="text: title"></h2>

    <pre data-bind="text: JSON.stringify(config, null, 4)"></pre>

    <pre data-bind="text: output"></pre>

    <table data-bind="foreach: exchangeRates">
        <tr>
            <td data-bind="text: currencyTo"></td>
            <td data-bind="text: rate"></td>
        </tr>
    </table>

    <ul data-bind="foreach: values">
        <li data-bind="text: $data"></li>
    </ul>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimple": {
                        "component": "Matozan_MagentoJs/js/knockout/plain-view-model",
                        "baseUrl": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
                    }
                }
            }
        }
    }
</script>
