<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div data-bind="scope: 'translate-component'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "translate-component": {
                        "component": "Matozan_MagentoJs/js/translate/component",
                        "template": "Matozan_MagentoJs/localized-template"
                    }
                }
            }
        }
    }
</script>
