<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<h1 data-mage-init='{"matozanTitle/title": {}}'></h1>

<pre class="target"></pre>

<div data-mage-init='{"Matozan_MagentoJs/js/requirejs/example-4": {"name": "Example 5"}}'></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Matozan_MagentoJs/js/requirejs/example": {},

            "Matozan_MagentoJs/js/requirejs/example-2": {},

            "Matozan_MagentoJs/js/requirejs/example-3": {
                "baseUrl": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            },

            "coffee": {
                "name": "Example 7 (Coffee)"
            }
        },

        ".target": {
            "Matozan_MagentoJs/js/requirejs/example-4": {
                "name": "Example 4"
            },

            "Matozan_MagentoJs/js/requirejs/example-6": {
                "name": "Example 6",
                "baseUrl": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            }
        }
    }
</script>
