<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<script type="text/x-magento-init">
    {
        "*": {
            "Matozan_MagentoJs/js/requirejs/example": {},

            "Matozan_MagentoJs/js/requirejs/example-2": {},

            "Matozan_MagentoJs/js/requirejs/example-3": {
                "baseUrl": "<?= $block->escapeJs($block->getBaseUrl()) ?>"
            }
        },

        ".target": {
            "Matozan_MagentoJs/js/requirejs/example-4": {
                "name": "Example 4"
            }
        }
    }
</script>

<div class="target"></div>

<div data-mage-init='{"Matozan_MagentoJs/js/requirejs/example-4": {"name": "Example 5"}}'></div>
