<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div id="my-collapsible">
    <div data-role="title">
        <h2>How 'bout a collapsible widget? <button data-role="trigger">GO</button></h2>
    </div>
    <div id="example" data-role="content"></div>
    <a href="<?= $block->getViewFileUrl('Matozan_MagentoJs/example-content.html') ?>"
       data-ajax="true"></a>
</div>

<script type="text/x-magento-init">
    {
        "#my-collapsible" : {
            "Matozan_MagentoJs/js/jquery/dynamic-collapsible": {
                "active": true,
                "saveState": true,
                "animate": {
                    "duration": 600,
                    "easing": "linear"
                },
                "ajaxContent": true
            }
        }
    }
</script>
