<div id="my-collapsible">
    <div data-role="title">
        <h2>How 'bout a collapsible widget? <button data-role="trigger">GO</button></h2>
    </div>
    <div id="example" data-role="content">
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
        This is the collapsible content right here!
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#my-collapsible" : {
            "collapsible": {
                "active": true,
                "saveState": true,
                "animate": {
                    "duration": 600,
                    "easing": "linear"
                }
            }
        }
    }
</script>
