<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<form data-mage-init='{"validation": {}}'>
    <div class="control">
        <input type="text" name="email" id="email" class="input-text"
               placeholder="<?= __('Your Email') ?>"
               data-validate="{required: true, 'validate-email': true}">
    </div>
    <button type="submit" class="action primary"><?= __('Submit') ?></button>
</form>
