<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div data-bind="scope: 'exampleUiComponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<div data-bind="scope: 'parentComponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "exampleUiComponent": {
                        "component": "Matozan_MagentoJs/js/ui/ui-component",
                        "label": "JSON label property",
                        "config" : {
                            "label": "JSON config.label property"
                        }
                    },
                    "parentComponent": {
                        "component": "uiComponent",
                        "template": "Matozan_MagentoJs/info",
                        "children": {
                            "child1": {
                                "component": "uiComponent",
                                "template": "Matozan_MagentoJs/info",
                                "children": {
                                    "child11": {
                                        "component": "uiComponent",
                                        "template": "Matozan_MagentoJs/info"
                                    }
                                }
                            },
                            "child2": {
                                "component": "uiComponent",
                                "template": "Matozan_MagentoJs/info"
                            }
                        }
                    }
                }
            }
        }
    }
</script>
