<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<div data-bind="scope: 'parent1'">
    <!-- ko foreach: getRegion('groupA') -->
        <!-- ko template: getTemplate() --><!-- /ko -->
    <!-- /ko -->
</div>

<div data-bind="scope: 'es5Observable'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "parent1": {
                        "component": "uiComponent",
                        "children": {
                            "child1": {
                                "component": "uiComponent",
                                "template": "Matozan_MagentoJs/info",
                                "displayArea": "groupA",
                                "children": {
                                    "child11": {
                                        "component": "uiComponent",
                                        "template": "Matozan_MagentoJs/info"
                                    }
                                }
                            },
                            "child2": {
                                "component": "uiComponent",
                                "template": "Matozan_MagentoJs/info",
                                "displayArea": "groupB"
                            },
                            "child3": {
                                "component": "uiComponent",
                                "template": "Matozan_MagentoJs/info",
                                "displayArea": "groupA"
                            }
                        }

                    },
                    "es5Observable": {
                        "component": "Matozan_MagentoJs/js/frontend-ui/es5-observable",
                        "template": "Matozan_MagentoJs/es5-observable"
                    }
                }
            }
        }
    }
</script>
